language: python
python:
  - "2.7"

env:
  matrix:
      - DJANGO_VERSION=1.5.5
      - DJANGO_VERSION=1.6.1

install:
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - pip install -r requirements_test.txt
  - pip install -e .

script:
  - django-admin.py test --settings=nested_formset.test_settings nested_formset
